### PR TITLE
Harder, better, faster, stronger

### PR DESCRIPTION
**Pull request by daxxog**
see #78

### CODE REVIEW

**Comment by paulopmx** [comment]
Is this the new pull request?

It still says:

Open daxxog wants to merge 2 commits into paulopmx:master  from daxxog:pull2

**Comment by daxxog** [comment]
This is a **new** pull request. Just now it's branched on my end as **pull2** and I am using "Windows style" newlines. I can't submit the request into anything except your master branch because _no other branches exist_. If you create a branch, I can re-submit the pull request into that branch. Or you can have people review my code on here. Whatever you prefer.

Thanks.

**Comment by paulopmx** [comment]
New branch created.

https://github.com/paulopmx/Flexigrid/tree/test

**Comment by daxxog** [comment]
alright, Ill re-submit.

**Pull request closed without merging**
