### PR TITLE
$.ajax cache fix for flexReload() issue

### PR DESCRIPTION
**Pull request by johnmbaughman**
This change has a fix for caching the AJAX data, which is a problem when flexReload is called.

I added a parameter `ajaxCache` which defaults to `false` so that the reload will work.

Then, I altered: 
`$.ajax({
    type: p.method,
    url: p.url,
    data: param,
    dataType: p.dataType,
    success: function (data) {
        g.addData(data);
    },
    error: function (XMLHttpRequest, textStatus, errorThrown) {
        try {
            if (p.onError) p.onError(XMLHttpRequest, textStatus, errorThrown);
        } catch (e) {}
    }
});`

To:
`$.ajax({
    cache: p.ajaxCache,
    type: p.method,
    url: p.url,
    data: param,
    dataType: p.dataType,
    success: function (data) {
        g.addData(data);
    },
    error: function (XMLHttpRequest, textStatus, errorThrown) {
        try {
            if (p.onError) p.onError(XMLHttpRequest, textStatus, errorThrown);
        } catch (e) {}
    }
});`

### CODE REVIEW

**Comment by paulopmx** [comment]
I can no longer pull this request. It's probably because I've pulled a newer code that doesn't include your changes.

**Comment by johnmbaughman** [comment]
I'll pull the latest myself and see about updating it and reposting another request. 

-John Baughman

**Comment by cljk** [comment]
Damn... I just forked the project to do the same because I had this issue today and saw later that you already started this fork. Nevertheless it was in the end not so important for me because I switched to POST because of a strange charset-error with IE.

**Comment by JohnRanger** [comment]
I have tried that fix. For added records, this works now fine but when I delete records, after a reload via the reload button within the flexigrid the deleted records still are there.

**Pull request closed without merging**
